name: club4care
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.2 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/club4care/assets/images/rectangle77.png
    - packages/club4care/assets/images/heartlock.png
    - packages/club4care/assets/images/line1.svg
    - packages/club4care/assets/images/line2.svg
    - packages/club4care/assets/images/ellipse1.png
    - packages/club4care/assets/images/clipboardcheck.svg
    - packages/club4care/assets/images/heartkey.png
    - packages/club4care/assets/images/rectangle2.svg
    - packages/club4care/assets/images/mail.svg
    - packages/club4care/assets/images/group.svg
    - packages/club4care/assets/images/arrowleftcircle.svg
